### ISSUE TITLE
Do you have a plan to release the code?

### ISSUE THREAD

**Issue by JaniceXiong** [rktamplayo/AceSum#1]
Thanks :)

**Comment by rktamplayo** [comment]
Yes, sorry I am currently busy with finishing up my dissertation. I will certainly upload the code this month once I clean it up :)

**Comment by JaniceXiong** [comment]
> Yes, sorry I am currently busy with finishing up my dissertation. I will certainly upload the code this month once I clean it up :)

Wow, hope everything goes well! And I still have little questions about the paper. 
At training time, reviews X is turned to z like format in Section 3.3 by selecting keywords and sentences relevant to y which is aspect-specific. But at inference time, we only got reviews X and what aspect we want, how to select keywords or sentences? And I also confused about [ASPECT] which is mentioned as "aspect code". But before that, aspect code also refer to ZD, ZS, ZT. Is aspect code a word, a vector or something else?
I am new to this domain and hope these questions don't disturb you.

**Comment by rktamplayo** [comment]
> At training time, reviews X is turned to z like format in Section 3.3 by selecting keywords and sentences relevant to y which is aspect-specific. But at inference time, we only got reviews X and what aspect we want, how to select keywords or sentences? And I also confused about [ASPECT] which is mentioned as "aspect code". But before that, aspect code also refer to ZD, ZS, ZT. Is aspect code a word, a vector or something else?

At inference time, given the target aspect that we want, we get aspect predictions at word and sentiment levels for each review. This would allow us to rank words/sentences and select those with higher probabilities.

The aspect codes are special tokens like [ROOM], [FOOD], etc. In the paper, we say that they are essentially doc-level aspect predictions z_D because we can transform z_D into multiple aspect codes (e.g., if z_D["ROOM"] is close to one, then use the [ROOM] aspect code). We did not say though that aspect codes also refer to z_S and z_T.

> I am new to this domain and hope these questions don't disturb you.

Thanks for your interest in this domain. Opinion summarization is currently very small, and we definitely want more people to work on this problem!

**Comment by JaniceXiong** [comment]
> The aspect codes are special tokens like [ROOM], [FOOD], etc. In the paper, we say that they are essentially doc-level aspect predictions z_D because we can transform z_D into multiple aspect codes (e.g., if z_D["ROOM"] is close to one, then use the [ROOM] aspect code). We did not say though that aspect codes also refer to z_S and z_T.

OK, it makes me clear about the format of z! 

> At inference time, given the target aspect that we want, we get aspect predictions at word and sentiment levels for each review. This would allow us to rank words/sentences and select those with higher probabilities.

At training time, we rank by comparing with ZD(y). And at inference time, we sort the predictions value at specific aspect column to select keywords and sentences. Is that right?

And I saw in Implementation section, "we select 10-best keywords, and review sentences truncated up to 500 tokens". If we want two or more aspects, how to split these fixed number of tokens and fixed length of sentences?

> Thanks for your interest in this domain. Opinion summarization is currently very small, and we definitely want more people to work on this problem!

Thanks a lot and It's very nice of you to give me kind and detailed reply 👍

**Comment by JaniceXiong** [comment]
> Yes, sorry I am currently busy with finishing up my dissertation. I will certainly upload the code this month once I clean it up :)

Hi! Is the code available now :)

**Comment by rktamplayo** [comment]
Hi thanks for the reminder. I added the code and seed words initially, I'll update again later with README instructions and the system outputs. For now, please have a look at the code :)

**Comment by rktamplayo** [comment]
> At training time, we rank by comparing with ZD(y). And at inference time, we sort the predictions value at specific aspect column to select keywords and sentences. Is that right?

Yes this is correct.

> And I saw in Implementation section, "we select 10-best keywords, and review sentences truncated up to 500 tokens". If we want two or more aspects, how to split these fixed number of tokens and fixed length of sentences?

The current method does not equally divide the keywords (e.g., 5 keywords each if there are two aspects), so this can certainly be improved by explicitly dividing them. A similar thing can be said for the sentences.

**Comment by JaniceXiong** [comment]
> Hi thanks for the reminder. I added the code and seed words initially, I'll update again later with README instructions and the system outputs. For now, please have a look at the code :)

wow! Thanks a lot for your hardworking and awesome work! Looking forward to further update and hope you have a nice day!

**Comment by rktamplayo** [comment]
Just updated again with all the necessary files!
