### ISSUE TITLE
Do you have a plan to update Readme recently?

### ISSUE THREAD

**Issue by yayahgh** [rktamplayo/AceSum#2]
Hi，dear author.
I read your paper and I am very interested in it. I want to reproduce AceSum. 
Do you have a plan to update Readme recently?

**Comment by patrycjakarolina** [comment]
Hi!

I second the above :) It will be very useful to get some more information about training specifics (e.g. how to adjust number of heads in relation to number of aspects) and format of the data (I see that it should be in `.jsonl` format but exact structure of training examples), minimum number of examples in train set etc. 

Looking forward to it - its a great work!

Pat

**Comment by rktamplayo** [comment]
Sorry for the long wait, and thanks for bugging me. Due to personal reasons, I had to skip this on my to-do list. Everything is updated with README and all the data/model/output files you need!
