### ISSUE TITLE
Questions regarding dataset and missing file.

### ISSUE THREAD

**Issue by tjsiledar** [rktamplayo/AceSum#5]
@rktamplayo It would be great if you could help me with a few questions regarding problems that I am facing while running the code.

1. I see that the train/dev/test file needs to have summaries as well. Is this a supervised summarization setting? Because I was of the notion that the paper introduced creation of synthetic datasets where the summaries where pseudo summaries selected from the input reviews. Can you clarify on how we can use some other data consisting of just raw customer reviews and produce general and aspect specific summaries for them? (No human annotated general or specific summary is available)

2. While running the train_sum.py I got the following error :
Traceback (most recent call last):
  File "src/train_sum.py", line 19, in <module>
    from calculate_rouge import calculate
ModuleNotFoundError: No module named 'calculate_rouge'

I guess the calculate_rouge file is missing in the repo. Can you please provide it?

Awaiting your response. Thanks in advance!!

**Comment by rktamplayo** [comment]
Sorry for the late response.

1. The summaries required by the summarization model are "pseudo-summaries". That is, they are created synthetically by the method described in the paper.
2. I have uploaded the missing file. Sorry again for the delay!
